name: Build Agents Action
description: Build country's agents into a docker image

inputs:
  country:
    required: true
    description: Country's agents
  githubToken:
    required: true
    description: Token to be used to install GPR packages and push GHCR images

runs:
  using: composite
  steps:
    - run: |
        cp ${{ github.action_path }}/Dockerfile . |
        cp ${{ github.action_path }}/.dockerignore . |
        cp ${{ github.action_path }}/fc-agents-init.sh .
      shell: bash
    - run: docker build --build-arg GIT_PASSWORD --tag ghcr.io/filmcalendar/fc-agents-${{ inputs.country }}:latest .
      shell: bash
      env:
        GIT_PASSWORD: ${{ inputs.githubToken }}
    - run: echo ${{ inputs.githubToken }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
      shell: bash
    - run: docker push ghcr.io/filmcalendar/fc-agents-${{ inputs.country }}:latest
      shell: bash
