name: Build Agents Action
description: Build country's agents into a docker image

inputs:
  country:
    required: true
    description: Country's agents
  dockerRegistryPassword:
    required: true
    description: Github token

env:
  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}

runs:
  using: composite
  steps:
    - run: |
        cp ${{ github.action_path }}/Dockerfile . |
        cp ${{ github.action_path }}/.dockerignore . |
        cp ${{ github.action_path }}/fc-agents-init.sh .
      shell: bash
    - run: docker build --build-arg GIT_PASSWORD --tag ghcr.io/filmcalendar/fc-agents-${{ inputs.country }}:latest .
      shell: bash
    - run: echo ${{ inputs.dockerRegistryPassword }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
      shell: bash
    - run: docker push ghcr.io/filmcalendar/fc-agents-${{ inputs.country }}:latest
      shell: bash
